### ISSUE TITLE
Error binding Parameter 8

### ISSUE THREAD

**Issue by 2ndNegative** [Gertje823/Vinted-Scraper#14]
I am receiving an unknown (to me) error.

```
runfile('D:/user/Downloads/Vinted-Scraper-main/Vinted-Scraper-main/scraper.py', wdir='D:/user/Downloads/Vinted-Scraper-main/Vinted-Scraper-main')
Creation of the directory failed or the folder already exists 
Creation of the directory failed or the folder already exists 
File already exists, skipped.
ID=46949382
Fetching page 1/2
User has more than 96 items. fetching next page....
Fetching page 2/2
Total items: 192
Creation of the directory downloads/46949382/ failed or the folder already exists 
Traceback (most recent call last):

  File "D:\user\Downloads\Vinted-Scraper-main\Vinted-Scraper-main\scraper.py", line 477, in <module>
    download_vinted_data(userids, session)

  File "D:\user\Downloads\Vinted-Scraper-main\Vinted-Scraper-main\scraper.py", line 258, in download_vinted_data
    c.execute("INSERT INTO Data(ID, User_id, Gender, Category, size, State, Brand, Colors, Price, Images, description, title, Platform)VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)", params)

InterfaceError: Error binding parameter 8 - probably unsupported type.
```

**Comment by Gertje823** [comment]
Vinted changed something in there API. They now return the price as a json object instead of a string.
This is solved in the latest version of the script
