### ISSUE TITLE
name 'r' is not defined

### ISSUE THREAD

**Issue by asdiasdiasdi** [Gertje823/Vinted-Scraper#21]
Error message is as follows:
Traceback (most recent call last):
  File "D:\Downloads\Vinted-Scraper-main\Vinted-Scraper-main\scraper.py", line 546, in <module>
    download_depop_data(userids)
  File "D:\Downloads\Vinted-Scraper-main\Vinted-Scraper-main\scraper.py", line 418, in download_depop_data
    elif r.status_code == 429:
NameError: name 'r' is not defined

**Comment by Gertje823** [comment]
Should be fixed now.
