### ISSUE TITLE
error running code

### ISSUE THREAD

**Issue by mblogs40** [Gertje823/Vinted-Scraper#38]
C:\Users\Admin\Downloads\python\Vinted-Scraper-2>python main.py -u 100625605
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\python\Vinted-Scraper-2\main.py", line 31, in <module>
    vinted_session = v.create_session()
  File "C:\Users\Admin\Downloads\python\Vinted-Scraper-2\Vinted.py", line 115, in create_session
    csrfToken = req.text.split('<meta name="csrf-token" content="')[1].split('"')[0]
IndexError: list index out of range

**Comment by mblogs40** [comment]
C:\Users\Admin\Downloads\python\Vinted-Scraper-main\Vinted-Scraper-main>python scraper.py
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\python\Vinted-Scraper-main\Vinted-Scraper-main\scraper.py", line 601, in <module>
    session = vinted_session()
  File "C:\Users\Admin\Downloads\python\Vinted-Scraper-main\Vinted-Scraper-main\scraper.py", line 61, in vinted_session
    csrfToken = req.text.split('<meta name="csrf-token" content="')[1].split('"')[0]
IndexError: list index out of range

**Comment by Gertje823** [comment]
I could not reproduce the issue. It looks like the script is not able to extract the csrf token. 
Are using a vpn/proxy to download?

**Comment by mblogs40** [comment]
no

**Comment by petecodes100** [comment]
I have the same issue regardless of IP address. Did the website change their code?
