### ISSUE TITLE
Depop 'products' issue

### ISSUE THREAD

**Issue by Laokza** [Gertje823/Vinted-Scraper#53]
Traceback (most recent call last):
  File "D:\Lol\Vinted-Scraper-main\scraper.py", line 709, in <module>
    download_depop_data(userids)
  File "D:\Lol\Vinted-Scraper-main\scraper.py", line 517, in download_depop_data
    get_all_depop_items(data, baseurl, product_ids, args, begin, s)
  File "D:\Lol\Vinted-Scraper-main\scraper.py", line 318, in get_all_depop_items
    for i in data['products']:
             ~~~~^^^^^^^^^^^^
KeyError: 'products'

**Comment by Laokza** [comment]
Traceback (most recent call last):
  File "D:\Lol\Vinted-Scraper-main\scraper.py", line 559, in download_depop_data
    Category = product_data['group']
               ~~~~~~~~~~~~^^^^^^^^^
KeyError: 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Lol\Vinted-Scraper-main\scraper.py", line 709, in <module>
    download_depop_data(userids)
  File "D:\Lol\Vinted-Scraper-main\scraper.py", line 561, in download_depop_data
    Category = product_data['categoryId']
               ~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'categoryId'

**Comment by Laokza** [comment]
First one when running with -d -g

Second one when running with -d only

**Comment by Laokza** [comment]
I've done a bit of testing with different sellers and I believe the issue may be with the videos. I'm by no means good at coding and whatnot so idk if that's the true issue but I'm able to download non videos just fine and when it gets to a video it errors. 
for source in x['sources']:

**Comment by Gertje823** [comment]
@Laokza Thanks, I will take a look at it this weekend. Do you have an example account that gives this error?

**Comment by Laokza** [comment]
Yes, lea_card is a perfect exemple since the first post contains a video. *At the time of writing this.* 
I'm able to download the first 3 images of the post but once it gets to the video it errors. 
Here's the full log: 
Traceback (most recent call last):
  File "D:\Lol\Vinted-Scraper-main\scraper.py", line 709, in <module>
    download_depop_data(userids)
  File "D:\Lol\Vinted-Scraper-main\scraper.py", line 661, in download_depop_data
    for source in x['sources']:
                  ~^^^^^^^^^^^
KeyError: 'sources'

**Comment by Gertje823** [comment]
Depop changed a field in the json response. I edited the code in [de59be3](https://github.com/Gertje823/Vinted-Scraper/commit/de59be39bc1245f8091b63aac3c83ea274b7400d) and it should be working now.

**Comment by Laokza** [comment]
Tested with new code and I'm getting this error:

Traceback (most recent call last):
  File "D:\Lol\Vinted-Scraper-main\scraper.py", line 563, in download_depop_data
    Category = product_data['group']
               ~~~~~~~~~~~~^^^^^^^^^
KeyError: 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Lol\Vinted-Scraper-main\scraper.py", line 713, in <module>
    download_depop_data(userids)
  File "D:\Lol\Vinted-Scraper-main\scraper.py", line 565, in download_depop_data
    Category = product_data['categoryId']
               ~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'categoryId'


Sorry for posting so many errors :/
