### ISSUE TITLE
Maximum amount of retries reached

### ISSUE THREAD

**Issue by exuded** [Gertje823/Vinted-Scraper#6]
Hi, thanks for your script! Unfortunately it doesn't work for me.
When I launch the script with Python Launcher, the terminal error is: 
`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/e/Downloads/Vinted-Scraper-main/scraper.py", line 342, in <module>
    session, params = vinted_session()
  File "/Users/e/Downloads/Vinted-Scraper-main/scraper.py", line 42, in vinted_session
    ua = UserAgent()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/fake_useragent/fake.py", line 75, in load
    self.data = load_cached(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/fake_useragent/utils.py", line 187, in load
    ret = json.loads(get(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached`

Can you help out? :)

**Comment by Gertje823** [comment]
It has something to do with the fake_useragent module. I removed the fake_useragent module and replaced it with a static user agent string. Could you download the latest version and see if it solves your issue?
